Models/User.cs
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace userdb.Models
{
    public class User : BaseEntity
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Level { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Description { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }

        [InverseProperty("Sender")]
        public List<Message> SentMessages { get; set; }

        [InverseProperty("Receiver")]
        public List<Message> ReceivedMessages { get; set; }

        public List<Comment> Comments { get; set; }

        public User()
        {
            SentMessages = new List<Message>();
            ReceivedMessages = new List<Message>();
            Comments = new List<Comment>();
        }

        public string FullName { 
            get {
                return this.FirstName + " " + this.LastName;
            }
        }

        public string LevelString {
            get {
                return this.Level == 1 ? "Admin" : "Normal";
            }
        }
    }
}

Models/UserViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;

namespace userdb.Models
{
    public class UserViewModel : BaseEntity
    {
        
        public int UserId { get; set; }

        [Required(ErrorMessage = "First name must be at least 4 characters long")]
        [MinLength(4)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Name can only contain letters")]
        [Display(Name="First name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last name must be at least 4 characters long")]
        [MinLength(4)]
        [Display(Name="Last name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please input a valid e-mail address")]
        [EmailAddress]
        // [EmailValidate(context)]
        public string Email { get; set; }

        public int Level { get; set; }
        
        [Required(ErrorMessage = "Password must be at least 4 characters long")]
        [DataType(DataType.Password)]
        [MinLength(4)]
        public string Password { get; set; }

        [Compare("Password", ErrorMessage = "Password and confirmation must match.")]
        [Display(Name="Confirm")]
        [DataType(DataType.Password)]
        public string PasswordConfirmation { get; set; }

        
    }

    //??? Not working, need a database connection?
    public class EmailValidateAttribute : ValidationAttribute
        {
        private static UserDBContext _context;
    
        public EmailValidateAttribute(UserDBContext context)
        {
            _context = context;
        }
            public override bool IsValid(object value)
            {
                bool IsExist = _context.Users.Any(r => r.Email == (string)value);
                if ( IsExist)
                {
                    return false;
                }
                return true;
            }
        }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using userdb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;

namespace userdb.Controllers
{
    public class UserController : Controller
    {
        private UserDBContext _context;
        public UserController(UserDBContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Route("Register")]
        public IActionResult Index()
        {
            if (IsUserLoggedIn()) return RedirectToAction("Dashboard", "User");
            return View("Register");
        }

        [HttpGet]
        [Route("users/new")]
        public IActionResult New()
        {
            return View("Add");
        }

        [HttpPost]
        [Route("Create")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(UserViewModel item)
        {
            if (_context.Users.Count() > 0) {
                if(_context.Users.Any(r => r.Email.ToLower() == item.Email.ToLower()))
                {
                    ModelState.AddModelError("Email", "Email address already exists. Please enter a different email address.");
                }
            }

            // As soon as the model is submitted TryValidateModel() is run for us, ModelState is already set
            if(ModelState.IsValid)
            {
                // Handle Success Case
                int level = 2; // Normal
                if(_context.Users.Count() == 0) {
                    level = 1; // Admin
                }
                User newUser = new User {
                    FirstName = item.FirstName,
                    LastName = item.LastName,
                    Email = item.Email,
                    Password = item.Password,
                    Level = level,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now
                };
                PasswordHasher<User> Hasher = new PasswordHasher<User>();
                newUser.Password = Hasher.HashPassword(newUser, newUser.Password);
    
                _context.Users.Add(newUser);
                _context.SaveChanges();
                HttpContext.Session.SetInt32("UserId", newUser.UserId);
                
                // if(newUser.Level == 1) return RedirectToAction("DashboardAdmin");

                return RedirectToAction("Dashboard");
            }
            return View("Register", item);
        }

        [HttpPost]
        [Route("CreateUser")]
        [ValidateAntiForgeryToken]
        public IActionResult CreateUser(UserViewModel item)
        {
            if (_context.Users.Count() > 0) {
                if(_context.Users.Any(r => r.Email.ToLower() == item.Email.ToLower()))
                {
                    ModelState.AddModelError("Email", "Email address already exists. Please enter a different email address.");
                }
            }

            // As soon as the model is submitted TryValidateModel() is run for us, ModelState is already set
            if(ModelState.IsValid)
            {
                // Handle Success Case
                int level = 2; // Normal
                if(_context.Users.Count() == 0) {
                    level = 1; // Admin
                }
                User newUser = new User {
                    FirstName = item.FirstName,
                    LastName = item.LastName,
                    Email = item.Email,
                    Password = item.Password,
                    Level = level,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now
                };
                PasswordHasher<User> Hasher = new PasswordHasher<User>();
                newUser.Password = Hasher.HashPassword(newUser, newUser.Password);
    
                _context.Users.Add(newUser);
                _context.SaveChanges();

                return RedirectToAction("Dashboard");
            }
            return View("Register", item);
        }

        [HttpGet]
        [Route("Login")]
        public IActionResult Login()
        {
            if (IsUserLoggedIn()) return RedirectToAction("Dashboard", "User");
            return View("Login");
        }

        [HttpPost]
        [Route("VerifyLogin")]
        [ValidateAntiForgeryToken]
        public IActionResult VerifyLogin(string Email, string Password)
        {
            string PasswordToCheck = Password;
            // Attempt to retrieve a user from your database based on the Email submitted
            var user = _context.Users.SingleOrDefault(r => r.Email == Email);
            if(user != null && PasswordToCheck != null)
            {
                var Hasher = new PasswordHasher<User>();
                // Pass the user object, the hashed password, and the PasswordToCheck
                if(0 != Hasher.VerifyHashedPassword(user, user.Password, PasswordToCheck))
                {
                    //Handle success
                    HttpContext.Session.SetInt32("UserId", user.UserId);
                    // if (user.Level == 1) {
                    //     return RedirectToAction("DashboardAdmin");
                    // }
                    return RedirectToAction("Dashboard");
                }
            }

            //Handle failure
            return RedirectToAction("Login");
        }

        [HttpGet]
        [Route("logout")]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }

        [HttpGet]
        [Route("dashboard")]
        public IActionResult Dashboard()
        {
            if (!IsUserLoggedIn()) return RedirectToAction("Login", "User");
            
            IEnumerable<User> AllUsers = _context.Users.OrderBy(r => r.FullName).ToList();
            User CurrentUser = _context.Users.SingleOrDefault(r => r.UserId == HttpContext.Session.GetInt32("UserId"));
            ViewBag.Users = AllUsers;
            if (CurrentUser.Level == 1) {
                return View("DashboardAdmin");
            }
            return View("Dashboard");
        }
        
        // [HttpGet]
        // [Route("users/show/{UserId}")]
        // public IActionResult Show(int UserId)
        // {
        //     if (!IsUserLoggedIn()) return RedirectToAction("Login", "User");

        //     User TheUser = _context.Users.SingleOrDefault(r => r.UserId == UserId);
        //     ViewBag.User = TheUser;
        //     return View("Show");
        // }

        // Show the inforamtion one the page to edit
        [HttpPost]
        [HttpGet]
        [Route("users/edit/{UserId}")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int UserId)
        {
            if (!IsUserLoggedIn()) return RedirectToAction("Login", "User");

            User EditUser = _context.Users.SingleOrDefault(r => r.UserId == UserId);
            // ViewBag.User = EditUser;
            UserInformationViewModel item = new UserInformationViewModel();
            item.FirstName = EditUser.FirstName;
            item.LastName = EditUser.LastName;
            item.Email = EditUser.Email;
            item.UserId = EditUser.UserId;
            item.Level = EditUser.Level;

            ViewBag.User = EditUser;
            // Using Partial ... @Html.Partial
            ViewBag.Password = new UserPasswordViewModel();
            ViewBag.ShowDescription = item.UserId == HttpContext.Session.GetInt32("UserId");
            return View("Edit", item);
        }

        // Show the inforamtion one the page to edit
        [HttpPost]
        [Route("UpdateUser")]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateUser(UserInformationViewModel item)
        {
            if (_context.Users.Count() > 0) {
                if(_context.Users.Any(r => 
                    r.Email.ToLower() == item.Email.ToLower() 
                    && r.UserId != item.UserId))
                {
                    ModelState.AddModelError("Email", "Email address already exists. Please enter a different email address.");
                }
            }
            User EditUser = _context.Users.SingleOrDefault(r => r.UserId == item.UserId);
            if(ModelState.IsValid)
            {
                EditUser.FirstName = item.FirstName;
                EditUser.LastName = item.LastName;
                EditUser.Email = item.Email;
                EditUser.Level = item.Level;
                EditUser.UpdatedAt = DateTime.Now;
                _context.Users.Update(EditUser);
                _context.SaveChanges();

                return RedirectToAction("Dashboard");
            }
            ViewBag.User = EditUser;
            // Using Partial ... @Html.Partial
            ViewBag.Password = new UserPasswordViewModel();
            ViewBag.ShowDescription = item.UserId == HttpContext.Session.GetInt32("UserId");
            return View("Edit", item);
        }

        // Show the inforamtion one the page to edit
        [HttpPost]
        [Route("UpdatePassword")]
        [ValidateAntiForgeryToken]
        public IActionResult UpdatePassword(UserPasswordViewModel item)
        {
            User EditUser = _context.Users.SingleOrDefault(r => r.UserId == item.UserId);
            if(ModelState.IsValid)
            {
                EditUser.Password = item.Password;
                EditUser.UpdatedAt = DateTime.Now;

                PasswordHasher<User> Hasher = new PasswordHasher<User>();
                EditUser.Password = Hasher.HashPassword(EditUser, EditUser.Password);

                _context.Users.Update(EditUser);
                _context.SaveChanges();

                return RedirectToAction("Dashboard");
            }

            ViewBag.User = EditUser;
            UserInformationViewModel vUser = new UserInformationViewModel();

Controllers/WallController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using userdb.Models;

namespace userdb.Controllers
{
    public class WallController : Controller
    {
        private UserDBContext _context;
        public WallController(UserDBContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Route("users/show/{UserId}")]
        public IActionResult ShowUser(int UserId)
        {
            if (!IsUserLoggedIn()) return RedirectToAction("Login", "User");
            User EditUser = _context.Users

                            .Include(r => r.ReceivedMessages)
                                .ThenInclude(r => r.Sender)
                                .ThenInclude(r => r.Comments)
                            .SingleOrDefault(r => r.UserId == UserId);

            ViewBag.User = EditUser;
            
            return View("Show");
        }

        [HttpPost]
        [Route("Wall/PostMessage")]
        [ValidateAntiForgeryToken]
        public IActionResult PostMessage(string message, int UserId)
        {
            Message newMessage = new Message();
            newMessage.MessageText = message;
            newMessage.ReceiverUserId = UserId;
            newMessage.SenderUserId = (int)HttpContext.Session.GetInt32("UserId");
            newMessage.CreatedAt = DateTime.Now;
            newMessage.UpdatedAt = DateTime.Now;

            _context.Messages.Add(newMessage);
            _context.SaveChanges();

            return RedirectToAction("ShowUser", new { UserId = UserId });
        }

        [HttpPost]
        [Route("Wall/PostComment")]
        [ValidateAntiForgeryToken]
        public IActionResult PostComment(string comment, int MessageId, int UserId)
        {
            Comment newComment = new Comment();
            newComment.MessageId = MessageId;
            newComment.CommentText = comment;
            newComment.UserId = (int)HttpContext.Session.GetInt32("UserId");
            newComment.CreatedAt = DateTime.Now;
            newComment.UpdatedAt = DateTime.Now;

            _context.Comments.Add(newComment);
            _context.SaveChanges();

            return RedirectToAction("ShowUser", new { UserId = UserId });
        }

        private bool IsUserLoggedIn()
        {
            if (HttpContext.Session.GetInt32("UserId") == null || HttpContext.Session.GetInt32("UserId") == 0 ) {
                return false;
            } else {
                return true;
            }
        }
    }
}

Views/User/Add.cshtml
@{
    ViewData["Title"] = "Register";
}
@model userdb.Models.UserViewModel

<div class="wells wells-sm">
    
    <form asp-controller="User" asp-action="CreateUser" method="post">
        <div class="form-horizontal">
        <h3>Add a new user</h3>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="FirstName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="LastName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Password" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PasswordConfirmation" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PasswordConfirmation" class="form-control" />
                <span asp-validation-for="PasswordConfirmation" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

    </form>
    
</div>

Views/User/Dashboard.cshtml
@{
    ViewData["Title"] = "Add a new cutomer";
}

<div class="wells wells-sm">
    <h3>Manage Users</h3>
    <div class="wells wells-sm">
        <table class="table table-striped table-bordered">
            <tr>
                <td>ID</td>
                <th>Name</th>
                <th>Email</th>
                <th>Created At</th>
                <th>User Level</th>

            </tr>
        @foreach(var r in @ViewBag.Users) {
            <tr>
                <td>@r.UserId</td>
                <td>
                    <a asp-controller="Wall" asp-action="ShowUser" asp-route-UserId="@r.UserId">@r.FullName</a>
                </td>
                <td>@r.Email</td>
                <td>@r.CreatedAt.ToString("MMM dd, yyyy ")</td>
                <td>@r.LevelString</td>
            </tr>
        }
        </table>
    </div>
</div>

Views/User/DashboardAdmin.cshtml
@{
    ViewData["Title"] = "Add a new cutomer";
}

<div class="wells wells-sm">
    <h3>Manage Users</h3>
    <a class="btn btn-primary" asp-controller="User" asp-action="New">Add new</a>
    <div class="wells wells-sm">
        <table class="table table-striped table-bordered">
            <tr>
                <td>ID</td>
                <th>Name</th>
                <th>Email</th>
                <th>Created At</th>
                <th>User Level</th>
                <th colspan="2" class="text-center">Actions</th>
            </tr>
        @foreach(var r in @ViewBag.Users) {
            <tr>
                <td>@r.UserId</td>
                <td><a asp-controller="Wall" asp-action="ShowUser" asp-route-UserId="@r.UserId">@r.FullName</a></td>
                <td>@r.Email</td>
                <td>@r.CreatedAt.ToString("MMM, dd yyyy")</td>
                <td>@r.LevelString</td>
                <td>
                    <form action="/users/edit/@r.UserId" method="post">
                        @Html.AntiForgeryToken()
                        <button type="submit" class="btn btn-link ">Edit</button>
                    </form>
                    
                </td>
                <td>
                    <form action="/Users/Delete/@r.UserId" method="post">
                        @Html.AntiForgeryToken()
                        <button type="submit" class="btn btn-link ">Remove</button>
                    </form>
                </td>
            </tr>
        }
        </table>
    </div>
</div>

Views/User/Edit.cshtml
@{
    ViewData["Title"] = "Register";
}
@using userdb.Models
@model userdb.Models.UserInformationViewModel
<hr />
<div class="container wells wells-sm">
    <div class="row">
        <div class="col-sm-7">
            <div class="panel panel-default edit-profile">
                <div class="panel-heading">Edit Information</div>
                <div class="panel-body">
                    <form asp-controller="User" asp-action="UpdateUser" method="post">
                        <input type="hidden" name="UserId" value="@ViewBag.User.UserId">
                        <div class="form-horizontal">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="FirstName" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="FirstName" class="form-control" />
                                    <span asp-validation-for="FirstName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="LastName" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="LastName" class="form-control" />
                                    <span asp-validation-for="LastName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="Email" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="Email" class="form-control" />
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="Level" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <select asp-for="Level" class="form-control">
                                        @{ var Admin = @ViewBag.User.UserId == 1 ? "Selected" : ""; }
                                        @{ var Normal = @ViewBag.User.UserId == 2 ? "Selected" : ""; }
                                        <option value="1" @Admin>Admin</option>
                                        <option value="2" @Normal>Normal</option>
                                    </select>
                                    <span asp-validation-for="Level" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Update" class="btn btn-default" />
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>

@Html.Partial("EditPasswordPartial", (UserPasswordViewModel)@ViewBag.Password)

    </div>
</div>

@if(ViewBag.ShowDescription) {
<div class="container wells wells-sm">
    <div class="row">
        <div class="panel panel-default edit-profile">
            <div class="panel-heading">Edit Description</div>
            <div class="panel-body">
                <form asp-controller="User" asp-action="UpdateDescription" method="post">
                    <input type="hidden" name="UserId" value="@ViewBag.User.UserId">
                    <div class="form-horizontal">
                        
                        <div class="form-group">
                            <div class="col-md-10">
                                <textarea name="Description" id="Description" cols="30" rows="10">@ViewBag.User.Description</textarea>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>  
}

Views/User/EditPasswordPartial.cshtml
@model userdb.Models.UserPasswordViewModel
        <div class="col-sm-5">
            <div class="panel panel-default">
            <div class="panel-heading">Change Password</div>
            <div class="panel-body">
                <form asp-controller="User" asp-action="UpdatePassword" method="post">
                    <input type="hidden" name="UserId" value="@ViewBag.User.UserId">
                    
                    <div class="form-horizontal">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        
                        <div class="form-group">
                            <label asp-for="Password" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="Password" class="form-control" />
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="PasswordConfirmation" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="PasswordConfirmation" class="form-control" />
                                <span asp-validation-for="PasswordConfirmation" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Update Password" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
   

Views/User/Login.cshtml
@{
    ViewData["Title"] = "Login";
}
@model userdb.Models.UserViewModel

<div class="wells wells-sm">
    
    <form asp-controller="User" asp-action="VerifyLogin" method="post">
        <div class="form-horizontal">
        <h3>Login</h3>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Password" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
    
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>

    </form>
    <p>Don't have an account? <a asp-controller="User" asp-action="Index">Register</a></p>
</div>

Views/User/Register.cshtml
@{
    ViewData["Title"] = "Register";
}
@model userdb.Models.UserViewModel

<div class="wells wells-sm">
    
    <form asp-controller="User" asp-action="Create" method="post">
        <div class="form-horizontal">
        <h3>Register a new user</h3>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="FirstName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="LastName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Password" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PasswordConfirmation" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PasswordConfirmation" class="form-control" />
                <span asp-validation-for="PasswordConfirmation" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

    </form>
    <p>Alaready a memeber? <a asp-controller="User" asp-action="Login">Login</a></p>
</div>